name: API Pinger

on:
  schedule:
    # Runs every 14 minutes.
    - cron: '*/14 * * * *'
  workflow_dispatch:
    # Allows you to run this workflow manually from the Actions tab

jobs:
  ping:
    runs-on: ubuntu-latest
    env:
      API_URL: https://nmusic.onrender.com/
    steps:
      - name: Wait for 50 seconds before starting
        run: sleep 50s
      
      - name: Checkout repository content
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      -  name: Install dependencies
         run: pip install requests

      -  name: Run the ping script
         run: python pinger.py # Make sure your python file is named this

